# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/healthhelper/msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/healthhelper/msg.proto',
  package='healthhelper',
  syntax='proto3',
  serialized_pb=_b('\n\x1cproto/healthhelper/msg.proto\x12\x0chealthhelper\"&\n\x04\x42ody\x12\x0f\n\x07xueyang\x18\x01 \x01(\x05\x12\r\n\x05xinlv\x18\x02 \x01(\x05\x42\x33\n%com.leadroyal.isee.healthhelper.protoB\nHealthDatab\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BODY = _descriptor.Descriptor(
  name='Body',
  full_name='healthhelper.Body',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xueyang', full_name='healthhelper.Body.xueyang', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xinlv', full_name='healthhelper.Body.xinlv', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['Body'] = _BODY

Body = _reflection.GeneratedProtocolMessageType('Body', (_message.Message,), dict(
  DESCRIPTOR = _BODY,
  __module__ = 'proto.healthhelper.msg_pb2'
  # @@protoc_insertion_point(class_scope:healthhelper.Body)
  ))
_sym_db.RegisterMessage(Body)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n%com.leadroyal.isee.healthhelper.protoB\nHealthData'))
# @@protoc_insertion_point(module_scope)
