// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/healthhelper/msg.proto

package com.leadroyal.isee.healthhelper.proto;

public final class HealthData {
  private HealthData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:healthhelper.Body)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 xueyang = 1;</code>
     */
    boolean hasXueyang();
    /**
     * <code>required int32 xueyang = 1;</code>
     */
    int getXueyang();

    /**
     * <code>required int32 xinlv = 2;</code>
     */
    boolean hasXinlv();
    /**
     * <code>required int32 xinlv = 2;</code>
     */
    int getXinlv();

    /**
     * <code>required int64 time = 3;</code>
     */
    boolean hasTime();
    /**
     * <code>required int64 time = 3;</code>
     */
    long getTime();
  }
  /**
   * Protobuf type {@code healthhelper.Body}
   */
  public  static final class Body extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:healthhelper.Body)
      BodyOrBuilder {
    // Use Body.newBuilder() to construct.
    private Body(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Body() {
      xueyang_ = 0;
      xinlv_ = 0;
      time_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Body(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              xueyang_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              xinlv_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              time_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leadroyal.isee.healthhelper.proto.HealthData.internal_static_healthhelper_Body_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leadroyal.isee.healthhelper.proto.HealthData.internal_static_healthhelper_Body_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leadroyal.isee.healthhelper.proto.HealthData.Body.class, com.leadroyal.isee.healthhelper.proto.HealthData.Body.Builder.class);
    }

    private int bitField0_;
    public static final int XUEYANG_FIELD_NUMBER = 1;
    private int xueyang_;
    /**
     * <code>required int32 xueyang = 1;</code>
     */
    public boolean hasXueyang() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 xueyang = 1;</code>
     */
    public int getXueyang() {
      return xueyang_;
    }

    public static final int XINLV_FIELD_NUMBER = 2;
    private int xinlv_;
    /**
     * <code>required int32 xinlv = 2;</code>
     */
    public boolean hasXinlv() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 xinlv = 2;</code>
     */
    public int getXinlv() {
      return xinlv_;
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <code>required int64 time = 3;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasXueyang()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasXinlv()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, xueyang_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, xinlv_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, time_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, xueyang_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, xinlv_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.leadroyal.isee.healthhelper.proto.HealthData.Body)) {
        return super.equals(obj);
      }
      com.leadroyal.isee.healthhelper.proto.HealthData.Body other = (com.leadroyal.isee.healthhelper.proto.HealthData.Body) obj;

      boolean result = true;
      result = result && (hasXueyang() == other.hasXueyang());
      if (hasXueyang()) {
        result = result && (getXueyang()
            == other.getXueyang());
      }
      result = result && (hasXinlv() == other.hasXinlv());
      if (hasXinlv()) {
        result = result && (getXinlv()
            == other.getXinlv());
      }
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && (getTime()
            == other.getTime());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasXueyang()) {
        hash = (37 * hash) + XUEYANG_FIELD_NUMBER;
        hash = (53 * hash) + getXueyang();
      }
      if (hasXinlv()) {
        hash = (37 * hash) + XINLV_FIELD_NUMBER;
        hash = (53 * hash) + getXinlv();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTime());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.leadroyal.isee.healthhelper.proto.HealthData.Body parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leadroyal.isee.healthhelper.proto.HealthData.Body parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leadroyal.isee.healthhelper.proto.HealthData.Body parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leadroyal.isee.healthhelper.proto.HealthData.Body parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leadroyal.isee.healthhelper.proto.HealthData.Body parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leadroyal.isee.healthhelper.proto.HealthData.Body parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leadroyal.isee.healthhelper.proto.HealthData.Body parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.leadroyal.isee.healthhelper.proto.HealthData.Body parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leadroyal.isee.healthhelper.proto.HealthData.Body parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leadroyal.isee.healthhelper.proto.HealthData.Body parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leadroyal.isee.healthhelper.proto.HealthData.Body prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code healthhelper.Body}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:healthhelper.Body)
        com.leadroyal.isee.healthhelper.proto.HealthData.BodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leadroyal.isee.healthhelper.proto.HealthData.internal_static_healthhelper_Body_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leadroyal.isee.healthhelper.proto.HealthData.internal_static_healthhelper_Body_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leadroyal.isee.healthhelper.proto.HealthData.Body.class, com.leadroyal.isee.healthhelper.proto.HealthData.Body.Builder.class);
      }

      // Construct using com.leadroyal.isee.healthhelper.proto.HealthData.Body.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        xueyang_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        xinlv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leadroyal.isee.healthhelper.proto.HealthData.internal_static_healthhelper_Body_descriptor;
      }

      public com.leadroyal.isee.healthhelper.proto.HealthData.Body getDefaultInstanceForType() {
        return com.leadroyal.isee.healthhelper.proto.HealthData.Body.getDefaultInstance();
      }

      public com.leadroyal.isee.healthhelper.proto.HealthData.Body build() {
        com.leadroyal.isee.healthhelper.proto.HealthData.Body result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leadroyal.isee.healthhelper.proto.HealthData.Body buildPartial() {
        com.leadroyal.isee.healthhelper.proto.HealthData.Body result = new com.leadroyal.isee.healthhelper.proto.HealthData.Body(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.xueyang_ = xueyang_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.xinlv_ = xinlv_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leadroyal.isee.healthhelper.proto.HealthData.Body) {
          return mergeFrom((com.leadroyal.isee.healthhelper.proto.HealthData.Body)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leadroyal.isee.healthhelper.proto.HealthData.Body other) {
        if (other == com.leadroyal.isee.healthhelper.proto.HealthData.Body.getDefaultInstance()) return this;
        if (other.hasXueyang()) {
          setXueyang(other.getXueyang());
        }
        if (other.hasXinlv()) {
          setXinlv(other.getXinlv());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasXueyang()) {
          return false;
        }
        if (!hasXinlv()) {
          return false;
        }
        if (!hasTime()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leadroyal.isee.healthhelper.proto.HealthData.Body parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leadroyal.isee.healthhelper.proto.HealthData.Body) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int xueyang_ ;
      /**
       * <code>required int32 xueyang = 1;</code>
       */
      public boolean hasXueyang() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 xueyang = 1;</code>
       */
      public int getXueyang() {
        return xueyang_;
      }
      /**
       * <code>required int32 xueyang = 1;</code>
       */
      public Builder setXueyang(int value) {
        bitField0_ |= 0x00000001;
        xueyang_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 xueyang = 1;</code>
       */
      public Builder clearXueyang() {
        bitField0_ = (bitField0_ & ~0x00000001);
        xueyang_ = 0;
        onChanged();
        return this;
      }

      private int xinlv_ ;
      /**
       * <code>required int32 xinlv = 2;</code>
       */
      public boolean hasXinlv() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 xinlv = 2;</code>
       */
      public int getXinlv() {
        return xinlv_;
      }
      /**
       * <code>required int32 xinlv = 2;</code>
       */
      public Builder setXinlv(int value) {
        bitField0_ |= 0x00000002;
        xinlv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 xinlv = 2;</code>
       */
      public Builder clearXinlv() {
        bitField0_ = (bitField0_ & ~0x00000002);
        xinlv_ = 0;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>required int64 time = 3;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required int64 time = 3;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 time = 3;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:healthhelper.Body)
    }

    // @@protoc_insertion_point(class_scope:healthhelper.Body)
    private static final com.leadroyal.isee.healthhelper.proto.HealthData.Body DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leadroyal.isee.healthhelper.proto.HealthData.Body();
    }

    public static com.leadroyal.isee.healthhelper.proto.HealthData.Body getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Body>
        PARSER = new com.google.protobuf.AbstractParser<Body>() {
      public Body parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Body(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Body> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Body> getParserForType() {
      return PARSER;
    }

    public com.leadroyal.isee.healthhelper.proto.HealthData.Body getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_healthhelper_Body_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_healthhelper_Body_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034proto/healthhelper/msg.proto\022\014healthhe" +
      "lper\"4\n\004Body\022\017\n\007xueyang\030\001 \002(\005\022\r\n\005xinlv\030\002" +
      " \002(\005\022\014\n\004time\030\003 \002(\003B3\n%com.leadroyal.isee" +
      ".healthhelper.protoB\nHealthData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_healthhelper_Body_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_healthhelper_Body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_healthhelper_Body_descriptor,
        new java.lang.String[] { "Xueyang", "Xinlv", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
